name: ✅ Checks

on:
  workflow_dispatch:
  pull_request:
  release:
    types:
      - published
      - deleted
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 0"

jobs:
  ci:
    uses: libhal/ci/.github/workflows/library_check.yml@5.x.y
    secrets: inherit
